### ISSUE TITLE
MIUI14语音唤醒由于xmsf框架导致FC

### ISSUE THREAD

**Issue by KagaJiankui** [NihilityT/MiPushFramework#14]
**Describe the bug/**
安装xmsf和mipush模块后小爱语音注册推送导致语音唤醒apk崩溃

**To Reproduce**
Steps to reproduce the behavior:（如何复现错误，也就是您的操作步骤）
1. 安装xmsf和mipush模块，给小爱语音注册xmsf模块推送
2. 等待一会或录制小爱语音唤醒词
3. 无法使用小爱同学的语音唤醒功能，语音唤醒APP发生FC，从小爱同学设置界面点进语音唤醒功能也发生FC

**Expected behavior**
A clear and concise description of what you expected to happen.（您希望发生什么）
小爱同学语音唤醒功能可以正常使用

**Logs** （日志）
Logs are very important, this can help us solve the problem.
Please upload your log file and paste the address here:（请上传您的日志文件，在这里粘贴地址：）
``` log
[ 2023-02-23T23:27:10.965    10175: 11533: 11840 E/AndroidRuntime  ] FATAL EXCEPTION: Connection Controller Thread
Process: com.miui.voicetrigger, PID: 11533
java.lang.IllegalArgumentException: com.miui.voicetrigger: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:404)
	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:674)
	at android.app.PendingIntent.getBroadcast(PendingIntent.java:661)
	at com.xiaomi.push.ex.a(Unknown Source:13)
	at com.xiaomi.push.ex.a(Unknown Source:76)
	at com.xiaomi.push.ew.a(Unknown Source:41)
	at com.xiaomi.push.service.XMPushService.e(Unknown Source:13)
	at com.xiaomi.push.service.XMPushService.a(Unknown Source:0)
	at com.xiaomi.push.service.bx.a(Unknown Source:2)
	at com.xiaomi.push.service.av.a(Unknown Source:52)
	at com.xiaomi.push.service.XMPushService.a(Unknown Source:127)
	at com.xiaomi.push.service.XMPushService.c(Unknown Source:1910)
	at com.xiaomi.push.service.XMPushService.a(Unknown Source:0)
	at com.xiaomi.push.service.XMPushService$h.a(Unknown Source:4)
	at com.xiaomi.push.service.XMPushService$i.run(Unknown Source:20)
	at com.xiaomi.push.service.h$c.run(Unknown Source:159)
[ 2023-02-23T23:27:11.326     1000:  2853:  8983 I/LSPosed-Bridge  ] [ INFO] 02-23 23:27:11 (PmsHookTarget33) @shouldFilterApplication: query from com.miui.voiceassist
[ 2023-02-23T23:27:11.329     1000: 11323: 12244 I/LSPosed-Bridge  ] [MIUIPerfSaver] config updated. supportFps: [120, 90, 60, 40, 30, 24], global: null, fpsMap: 0
[ 2023-02-23T23:27:14.019     1000:  2853:  3502 I/LSPosed-Bridge  ] [ INFO] 02-23 23:27:14 (ZygoteArgsHook) @startViaZygote force mount data: 10175 com.miui.voicetrigger
```

日志压缩包：
- 链接: [https://pan.baidu.com/s/1j3-lXGFOGsZOgMQsN1TiwQ?pwd=ursc](https://pan.baidu.com/s/1j3-lXGFOGsZOgMQsN1TiwQ?pwd=ursc)
- 提取码: ursc

**ROM and version(manager):** （你的 ROM 和 manager 的版本）
 - Name: MIUI 14
 - Android Version: 13
 - Version: V14.0.23.2.13.DEV

**Comment by duzhaokun123** [comment]
🤔 MIUI 为啥要用这个

**Comment by tengqian** [comment]
一样的问题,miui14，安装组件后，原小爱同学唤醒信息丢失，重新录入就报错。

**Comment by NihilityT** [comment]
确认 [v0.3.10](https://github.com/NihilityT/MiPushFramework/releases/tag/v0.3.10) 是否已解决

**Comment by powerAn2020** [comment]
> 将 [v0.3.10](https://github.com/NihilityT/MiPushFramework/releases/tag/v0.3.10) 安装为系统应用，确认问题是否已解决

目前在用xmsf 0.3.9版本已恢复正常，但之前有问题的系统是MIUI14开发版，现在系统是MIUI14稳定版，所以无法确认是不是MIUI系统导致的，抱歉大佬帮不上忙。 @NihilityT
