### ISSUE TITLE
通过KernelSU模块固化软件到系统时软件会崩溃闪退

### ISSUE THREAD

**Issue by SoDebug** [NihilityT/MiPushFramework#29]
**Describe the bug/**
A clear and concise description of what the bug is.（解释一下出了什么问题）

通过KernelSU模块固化软件到System/app/，重启系统卸载更新之后会导致软件崩溃闪退。

**To Reproduce**
Steps to reproduce the behavior:（如何复现错误，也就是您的操作步骤）
1. 安装软件本体
2. 提取软件本体及oat文件夹的所有内容打包为KernelSU模块
3. 安装模块，重启系统，为软件本体卸载更新（固化到系统的软件会自动安装，这里是卸载用户分区的软件）

**Expected behavior**
A clear and concise description of what you expected to happen.（您希望发生什么）

能正常运行软件

**Screenshots**（截图）

闪退无截图，无法进入软件界面

**Logs** （日志）
Logs are very important, this can help us solve the problem.
Please upload your log file and paste the address here:（请上传您的日志文件，在这里粘贴地址：）

time: 1693558883640
msg: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.content.res.Resources.getConfiguration()' on a null object reference
stacktrace: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.content.res.Resources.getConfiguration()' on a null object reference
	at android.app.ConfigurationController.updateLocaleListFromAppContext(ConfigurationController.java:271)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6714)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7966)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)

**ROM and version(manager):** （你的 ROM 和 manager 的版本）
 - Name: [e.g. Lineage OS]    Evolution X
 - Android Version: [e.g. 8.1]  13.0
 - Version [e.g. 0.3.4 stable]  0.3.11-3-g0585c7a9

**Additional context**
Add any other context about the problem here.（更多关于问题的内容写在这里）

**Comment by NihilityT** [comment]
安装后用爱玩机固化是否会出问题？

**Comment by NihilityT** [comment]
使用最新版本，直接核心破解安装。
