### ISSUE TITLE
停止运行

### ISSUE THREAD

**Issue by 253551464** [NihilityT/MiPushFramework#6]
**Describe the bug/**
A clear and concise description of what the bug is.（解释一下出了什么问题）
停止运行

**To Reproduce**
Steps to reproduce the behavior:（如何复现错误，也就是您的操作步骤）
开机自启的时候，显示停止运行

**Expected behavior**
A clear and concise description of what you expected to happen.（您希望发生什么）

**Screenshots**（截图）

**Logs** （日志）
Logs are very important, this can help us solve the problem.
Please upload your log file and paste the address here:（请上传您的日志文件，在这里粘贴地址：）
`time: 1672483865149
msg: android.app.StackTrace: Last startServiceCommon() call for this service was made here
stacktrace: android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{348679e u0 com.xiaomi.xmsf/com.xiaomi.push.service.PushServiceMain}
	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2005)
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:1976)
	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2241)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7868)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: android.app.StackTrace: Last startServiceCommon() call for this service was made here
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1915)
	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1870)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:822)
	at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(ContextCompat.java:931)
	at androidx.core.content.ContextCompat.startForegroundService(ContextCompat.java:703)
	at com.xiaomi.xmsf.push.service.XMPushService.forwardToPushServiceMain(XMPushService.java:106)
	at com.xiaomi.xmsf.push.service.XMPushService.onHandleIntent(XMPushService.java:46)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:78)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
`

**ROM and version(manager):** （你的 ROM 和 manager 的版本）
 - Name: Evolution X
 - Android Version: 13
 - Version 版本 0.3.7.20221026.92d4eb92

**Additional context**
Add any other context about the problem here.（更多关于问题的内容写在这里）

**Comment by NihilityT** [comment]
[0.3.7.20230108.41efec1](https://github.com/NihilityT/MiPushFramework/releases/tag/0.3.7.20230108.41efec1) 及之后的版本是否已修复？

**Comment by 253551464** [comment]
> [0.3.7.20230108.41efec1](https://github.com/NihilityT/MiPushFramework/releases/tag/0.3.7.20230108.41efec1) 及之后的版本是否已修复？

没有再出现停止运行的弹窗
