### ISSUE TITLE
停止运行

### ISSUE THREAD

**Issue by 253551464** [NihilityT/MiPushFramework#9]
**Describe the bug/**
A clear and concise description of what the bug is.（解释一下出了什么问题）
停止运行

**To Reproduce**
Steps to reproduce the behavior:（如何复现错误，也就是您的操作步骤）
看了一下通知记录，收到酷安的通知，然后停止运行

**Expected behavior**
A clear and concise description of what you expected to happen.（您希望发生什么）

**Screenshots**（截图）

**Logs** （日志）
Logs are very important, this can help us solve the problem.
Please upload your log file and paste the address here:（请上传您的日志文件，在这里粘贴地址：）
`time: 1674264502671
msg: java.lang.IllegalArgumentException: width and height must be > 0
stacktrace: java.lang.IllegalArgumentException: width and height must be > 0
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1111)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1078)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1028)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:989)
	at top.trumeet.common.utils.ImgUtils.cropTransparent(ImgUtils.java:166)
	at top.trumeet.common.utils.ImgUtils.convertToTransparentAndWhite(ImgUtils.java:111)
	at top.trumeet.common.cache.IconCache$WhiteIconProcess.convert(IconCache.java:122)
	at top.trumeet.common.cache.IconCache$3.gen(IconCache.java:93)
	at top.trumeet.common.cache.IconCache$3.gen(IconCache.java:86)
	at top.trumeet.common.cache.AbstractCacheAspect.get(AbstractCacheAspect.java:18)
	at top.trumeet.common.cache.IconCache.getIconCache(IconCache.java:96)
	at com.xiaomi.xmsf.push.notification.NotificationController.processIcon(NotificationController.java:371)
	at com.xiaomi.xmsf.push.notification.NotificationController.notify(NotificationController.java:226)
	at com.xiaomi.xmsf.push.notification.NotificationController.publish(NotificationController.java:212)
	at com.xiaomi.push.service.MyMIPushNotificationHelper.doNotifyPushMessage(MyMIPushNotificationHelper.java:314)
	at com.xiaomi.push.service.MyMIPushNotificationHelper.lambda$notifyPushMessage$0(MyMIPushNotificationHelper.java:156)
	at com.xiaomi.push.service.MyMIPushNotificationHelper$$ExternalSyntheticLambda1.run(Unknown Source:6)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
`

**ROM and version(manager):** （你的 ROM 和 manager 的版本）
 - Name: Evolution X
 - Android Version: 13
 - Version 0.3.7.20230120.c2d6eda

**Additional context**
Add any other context about the problem here.（更多关于问题的内容写在这里）

**Comment by 253551464** [comment]
> 在记录列表点击具体的记录项，点击「发出通知」，确认是哪一条导致的崩溃，把记录发上来看看。

`{
  "action": "SendMessage",
  "appid": "2882303761517155131",
  "encryptAction": true,
  "isRequest": false,
  "metaInfo": {
    "description": "关注了你",
    "extra": {
      "intent_uri": "tpns://com.coolapk.market?busiMsgId=1616608613076418560&c=NNfFZEN2h04ATFTDy3GAbdOrCm1Sq0%2Fam8M75rMioxCA1CVy10Ovax4Ck3ir85D4dzwX%2F%2Bi4dWD6laACxV7ZvA%3D%3D&checkCode=7e6aba8445acedfd1b810579548d6a48&customContent=%7B%22uid%22%3A1193904%2C%22fromuid%22%3A129848%2C%22fromusername%22%3A%22VSUN07%22%2C%22from_type%22%3A0%2C%22list_group%22%3A1%2C%22type%22%3A%22contacts_follow%22%2C%22slug%22%3A%228557f4230f509a4f6a5ec59945c04f0e%22%2C%22isnew%22%3A1%2C%22note%22%3A%22%5Cu5173%5Cu6ce8%5Cu4e86%5Cu4f60%5Cuff1a%3Ca+href%3D%5Cu0022%5C%2Fcontacts%5C%2Ffans%5Cu0022%3E%5Cu67e5%5Cu770b%3C%5C%2Fa%3E%22%2C%22dateline%22%3A1674264502%2C%22id%22%3A%22351181859%22%2C%22fromType%22%3A0%2C%22notifyType%22%3A%22contacts_follow%22%2C%22description%22%3A%22%5Cu5173%5Cu6ce8%5Cu4e86%5Cu4f60%22%2C%22fromUserAvatar%22%3A%22http%3A%5C%2F%5C%2Favatar.coolapk.com%5C%2Fdata%5C%2F000%5C%2F12%5C%2F98%5C%2F48_avatar_middle.jpg%3F1455811165%22%2C%22notifyCount%22%3A%7B%22cloudInstall%22%3A0%2C%22notification%22%3A4%2C%22contacts_follow%22%3A2%2C%22message%22%3A0%2C%22atme%22%3A0%2C%22atcommentme%22%3A0%2C%22commentme%22%3A0%2C%22feedlike%22%3A4%2C%22badge%22%3A8%2C%22dateline%22%3A1674264502%7D%7D&groupId=00%3A5211&jumpType=3&msgId=1616608613076418560&msgType=1&pushChannel=103&pushTime=1674264503&source=0&targetActivity=coolmarket%3A%2F%2Fwww.coolapk.com%2Fnotification%2FcontactsFollowList&targetType=4&timestamp=1674264503",
      "channel_name": "消息通知",
      "n_stats_expose": "WmXCiwoHV4mnybu5xRRFzBIoo7Hs04zXP10YLK1SKWICLxlDenRwza6MYPTDbmiXJtZlMJPRCmh3Ggn/eLykk7e+v7H/15x3rc3djnJdj90FV6sI5u3besjjgSOaDKpf",
      "rights_stat": "100000000",
      "callback.param": "ot2dbo              ca5rxcb87ytc 4            〰㨵㈱ㄠ",
      "__target_name": "sNpBgXnVvpTD867x/1s0fTKuZPZ/VFShCnJUd//CI5Q4FLprV3RjM5DwQoFlIuxt",
      "fe_ts": "1674264503182",
      "callback.type": "243",
      "callback": "https://stat.tpns.tencent.com/log/statistics/xm/1500007668",
      "notify_effect": "2",
      "__m_ts": "1674264503488",
      "channel_id": "5"
    },
    "id": "scm57389674264503182Bk",
    "ignoreRegInfo": false,
    "messageTs": 1674264503182,
    "notifyId": 2380745,
    "notifyType": 7,
    "passThrough": 0,
    "title": "VSUN07"
  },
  "packageName": "com.coolapk.market",
  "pushAction": {
    "cause": {
      "detailMessage": "error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT",
      "stackTrace": [],
      "suppressedExceptions": []
    },
    "detailMessage": "the aes decrypt failed.",
    "stackTrace": [],
    "suppressedExceptions": []
  },
  "target": {
    "channelId": 5,
    "isPreview": false,
    "resource": "an9fGSSA",
    "server": "xiaomi.com",
    "userId": "73461832163"
  }
}`

还有一个问题，图标不全
![Screenshot_20230121-101103_AIDE_Pro](https://user-images.githubusercontent.com/36783515/213839465-270ae3f0-f94d-4eda-b46a-a4665d98d6f1.png)

**Comment by NihilityT** [comment]
[0.3.7.20230108.41efec1](https://github.com/NihilityT/MiPushFramework/releases/tag/0.3.7.20230108.41efec1)
此版本是否存在问题？
QQ 邮箱 和 酷安 的图标长什么样？

**Comment by 253551464** [comment]
> [0.3.7.20230108.41efec1](https://github.com/NihilityT/MiPushFramework/releases/tag/0.3.7.20230108.41efec1) 此版本是否存在问题？ QQ 邮箱 和 酷安 的图标长什么样？

没有，
![Screenshot_20230121-104603_冰箱_IceBox](https://user-images.githubusercontent.com/36783515/213840534-e5b4d35f-3b9d-4140-80aa-6eb444764b78.png)

**Comment by NihilityT** [comment]
查看 [0.3.7.20230112.9e7fbb1f](https://github.com/NihilityT/MiPushFramework/releases/tag/0.3.7.20230112.9e7fbb1f) 的更新日志，先使用自定义图标绕开这个问题。
这个问题后面有时间再修复。
